bundler_args: --without development --path vendor/bundle
script: "bundle exec rake spec"
rvm:
        - 1.9.2
gemfile:
        - Gemfile
branches:
        only:
                - master
                - develop
